import { BarChart } from "@/components/charts/BarChart";
import { DonutChart } from "@/components/charts/DonutChart";
import { ModuleHeader } from "@/components/layout/ModuleHeader";
import { KpiCard } from "@/components/shared/KpiCard";
import { SectionPanel } from "@/components/shared/SectionPanel";
import { buildTicketReasonTokens } from "@/lib/ticket-classifier/reason-view-model";
import type { TicketClassifierAnalysis } from "@/lib/ticket-classifier/types";
import { SlaRiskPanel } from "./SlaRiskPanel";
import { TicketQueueTable } from "./TicketQueueTable";

export function TicketClassifierDashboard({
  analysis,
}: {
  analysis: TicketClassifierAnalysis;
}) {
  return (
    <div className="space-y-6">
      <ModuleHeader
        eyebrow="Urgent Ticket Classifier"
        title="Priority scoring for helpdesk and IT operations"
        description="Classifies helpdesk demand into urgent queues with explainable business impact, urgency, and recommended action summaries."
        aside={
          <div>
            <p className="font-mono text-[10px] uppercase tracking-[0.24em] text-[var(--nexus-text-muted)]">
              Dominant Priority
            </p>
            <p className="mt-2 text-3xl font-semibold text-[var(--nexus-text)]">
              {analysis.summary.dominantPriority}
            </p>
            <p className="mt-2 text-sm text-[var(--nexus-text-soft)]">
              {analysis.summary.p1P2Tickets} tickets currently need elevated routing.
            </p>
          </div>
        }
      />

      <section className="grid grid-cols-1 gap-4 md:grid-cols-2 2xl:grid-cols-4">
        <KpiCard
          label="Open Tickets"
          value={String(analysis.summary.openTickets)}
          description="Tickets still active in the current queue snapshot."
          riskLevel="medium"
          variant="green"
        />
        <KpiCard
          label="P1 / P2 Tickets"
          value={String(analysis.summary.p1P2Tickets)}
          description="Highest-priority queue load for immediate or same-shift action."
          riskLevel={analysis.summary.p1P2RiskLevel}
          variant="red"
        />
        <KpiCard
          label="SLA Breach Risk"
          value={String(analysis.summary.slaBreachRisk)}
          description="Tickets whose timing and priority indicate elevated SLA breach probability."
          riskLevel={analysis.summary.slaBreachRiskLevel}
          variant="orange"
        />
        <KpiCard
          label="Average Score"
          value={String(analysis.summary.averagePriorityScore)}
          description="Average ticket priority score generated by the deterministic classifier."
          riskLevel={analysis.summary.averagePriorityRiskLevel}
          variant="blue"
        />
      </section>

      <section className="grid grid-cols-1 gap-6 xl:grid-cols-[0.95fr_1.05fr]">
        <SectionPanel title="Priority Mix" eyebrow="Queue Shape">
          <DonutChart
            centerLabel="Queue"
            centerValue={String(analysis.items.length)}
            segments={analysis.priorityDistribution}
          />
        </SectionPanel>
        <SectionPanel title="Top Queue Categories" eyebrow="Operational Load">
          <BarChart items={analysis.categoryDistribution} />
        </SectionPanel>
      </section>

      <section>
        <SectionPanel title="Ticket Queue Table" eyebrow="Classification Output">
          <TicketQueueTable rows={analysis.items} />
        </SectionPanel>
      </section>

      <section className="grid grid-cols-1 gap-6 xl:grid-cols-2">
        <SlaRiskPanel analysis={analysis} />
        <SectionPanel title="Business Impact Summary" eyebrow="Queue Snapshot">
          <div className="grid min-w-0 gap-3">
            <div className="grid min-w-0 grid-cols-[1fr_auto] items-center gap-4 rounded-lg border border-[var(--nexus-border-subtle)] bg-[rgba(4,10,6,0.52)] p-4">
              <div className="min-w-0">
                <p className="break-words font-mono text-[10px] uppercase leading-5 tracking-[0.12em] text-[var(--nexus-text-muted)]">
                  Critical Impact Tickets
                </p>
                <p className="mt-1 text-sm leading-6 text-[var(--nexus-text-soft)]">
                  Highest business disruption in queue
                </p>
              </div>
              <p className="shrink-0 text-2xl font-semibold leading-none text-[var(--nexus-text)]">
                {analysis.summary.criticalImpactTickets}
              </p>
            </div>
            <div className="grid min-w-0 grid-cols-[1fr_auto] items-center gap-4 rounded-lg border border-[var(--nexus-border-subtle)] bg-[rgba(4,10,6,0.52)] p-4">
              <div className="min-w-0">
                <p className="break-words font-mono text-[10px] uppercase leading-5 tracking-[0.12em] text-[var(--nexus-text-muted)]">
                  Security-Related Tickets
                </p>
                <p className="mt-1 text-sm leading-6 text-[var(--nexus-text-soft)]">
                  Tickets with security triage signals
                </p>
              </div>
              <p className="shrink-0 text-2xl font-semibold leading-none text-[var(--nexus-text)]">
                {analysis.summary.securityRelatedTickets}
              </p>
            </div>
          </div>
        </SectionPanel>
      </section>

      <section>
        <SectionPanel title="Why These Tickets Are Urgent" eyebrow="Readable Reasons">
          <div className="grid grid-cols-1 gap-4 xl:grid-cols-3">
            {analysis.items.slice(0, 3).map((ticket) => (
              <div
                key={ticket.ticketId}
                className="flex min-h-[17rem] min-w-0 flex-col rounded-lg border border-[var(--nexus-border-subtle)] bg-[linear-gradient(180deg,rgba(34,197,94,0.08),rgba(4,10,6,0.58))] p-4"
              >
                <div className="flex min-h-0 flex-1 flex-col">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div className="min-w-0">
                      <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[var(--nexus-text-muted)]">
                        {ticket.ticketId} / {ticket.predictedPriority}
                      </p>
                      <p className="mt-2 text-sm font-semibold leading-6 text-[var(--nexus-text)]">
                        {ticket.title}
                      </p>
                    </div>
                    <div className="max-w-full shrink-0 rounded-full border border-[rgba(168,85,247,0.22)] bg-[rgba(168,85,247,0.08)] px-3 py-1 font-mono text-[10px] uppercase leading-5 tracking-[0.12em] text-[var(--nexus-purple)]">
                      urgent signal
                    </div>
                  </div>
                  <div className="mt-3 flex flex-wrap gap-2">
                    {buildTicketReasonTokens(ticket.classificationReason).map(
                      (token) => (
                        <span
                          key={`${ticket.ticketId}-${token.label}-${token.value}`}
                          className="min-w-0 max-w-full break-words rounded-full border border-[rgba(220,255,220,0.12)] bg-[rgba(220,255,220,0.05)] px-2.5 py-1 font-mono text-[10px] uppercase leading-5 tracking-[0.08em] text-[var(--nexus-text-soft)]"
                        >
                          <span className="text-[var(--nexus-text-muted)]">
                            {token.label}
                          </span>{" "}
                          {token.value}
                        </span>
                      )
                    )}
                  </div>
                  <div className="mt-auto min-w-0 rounded-lg border border-[rgba(34,197,94,0.14)] bg-[rgba(34,197,94,0.06)] px-3 py-2">
                    <p className="break-words font-mono text-[10px] uppercase leading-5 tracking-[0.12em] text-[var(--nexus-text-muted)]">
                      Recommended Action
                    </p>
                    <p className="mt-1 text-xs leading-6 text-[var(--nexus-green)]">
                      {ticket.recommendedAction}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </SectionPanel>
      </section>
    </div>
  );
}
