import { DashboardData } from "@/types/incident";

export const mockDashboardData: DashboardData = {
  source: "mock",
  summary: {
    open_tickets: 34,
    recurring_clusters: 9,
    high_risk_tickets: 7,
    top_services: ["Identity", "Customer Portal", "Network Core"],
    trends: [
      { date: "2026-04-21", count: 3 },
      { date: "2026-04-22", count: 5 },
      { date: "2026-04-23", count: 7 },
      { date: "2026-04-24", count: 4 },
      { date: "2026-04-25", count: 6 },
      { date: "2026-04-26", count: 8 },
      { date: "2026-04-27", count: 5 },
      { date: "2026-04-28", count: 3 },
      { date: "2026-04-29", count: 4 },
      { date: "2026-04-30", count: 2 },
    ],
  },
  recurring: [
    {
      signature: "access|identity|access",
      category: "Access",
      service: "Identity",
      keyword_bucket: "access",
      frequency: 8,
      last_seen: "2026-04-29",
      trend_delta: 3,
      sample_ticket_ids: ["INC-1001", "INC-1020", "INC-1028"],
      sample_titles: [
        "Users locked out after MFA reset",
        "Users locked out after MFA reset",
        "Users locked out after MFA reset",
      ],
    },
    {
      signature: "network|network core|network",
      category: "Network",
      service: "Network Core",
      keyword_bucket: "network",
      frequency: 7,
      last_seen: "2026-04-29",
      trend_delta: 2,
      sample_ticket_ids: ["INC-1002", "INC-1018", "INC-1030"],
      sample_titles: [
        "VPN disconnects for remote staff",
        "VPN disconnects for remote staff",
        "DNS resolution failure in branch office",
      ],
    },
    {
      signature: "application|customer portal|application",
      category: "Application",
      service: "Customer Portal",
      keyword_bucket: "application",
      frequency: 6,
      last_seen: "2026-04-28",
      trend_delta: 1,
      sample_ticket_ids: ["INC-1004", "INC-1008", "INC-1011"],
      sample_titles: [
        "Portal timeout during checkout",
        "Portal outage in EU region",
        "Checkout API returns 500 error",
      ],
    },
    {
      signature: "email|collaboration|email",
      category: "Email",
      service: "Collaboration",
      keyword_bucket: "email",
      frequency: 5,
      last_seen: "2026-04-28",
      trend_delta: 0,
      sample_ticket_ids: ["INC-1003", "INC-1010", "INC-1023"],
      sample_titles: [
        "Outlook mailbox sync delayed",
        "SMTP relay failure for alerts",
        "Outlook mailbox sync delayed",
      ],
    },
    {
      signature: "access|identity|access",
      category: "Access",
      service: "Identity",
      keyword_bucket: "access",
      frequency: 4,
      last_seen: "2026-04-26",
      trend_delta: -1,
      sample_ticket_ids: ["INC-1006", "INC-1024", "INC-1036"],
      sample_titles: [
        "Password reset emails not delivered",
        "Password reset emails not delivered",
        "Password reset emails not delivered",
      ],
    },
    {
      signature: "infrastructure|compute|infrastructure",
      category: "Infrastructure",
      service: "Compute",
      keyword_bucket: "infrastructure",
      frequency: 3,
      last_seen: "2026-04-27",
      trend_delta: 1,
      sample_ticket_ids: ["INC-1005", "INC-1027"],
      sample_titles: [
        "Low CPU alert on reporting VM",
        "Idle VM running in dev subscription",
      ],
    },
    {
      signature: "infrastructure|storage|infrastructure",
      category: "Infrastructure",
      service: "Storage",
      keyword_bucket: "infrastructure",
      frequency: 2,
      last_seen: "2026-04-24",
      trend_delta: 0,
      sample_ticket_ids: ["INC-1014", "INC-1035"],
      sample_titles: [
        "Unattached disk still incurring cost",
        "Unattached snapshot accumulation",
      ],
    },
    {
      signature: "application|customer portal|application",
      category: "Application",
      service: "Customer Portal",
      keyword_bucket: "application",
      frequency: 2,
      last_seen: "2026-04-23",
      trend_delta: -1,
      sample_ticket_ids: ["INC-1015"],
      sample_titles: ["Search endpoint degraded"],
    },
    {
      signature: "access|identity|access",
      category: "Access",
      service: "Identity",
      keyword_bucket: "access",
      frequency: 2,
      last_seen: "2026-04-23",
      trend_delta: 0,
      sample_ticket_ids: ["INC-1016", "INC-1040"],
      sample_titles: [
        "MFA code delivery delayed",
        "OTP provider latency increased",
      ],
    },
  ],
  priorities: [
    {
      ticket_id: "INC-1008",
      title: "Portal outage in EU region",
      category: "Application",
      service: "Customer Portal",
      status: "Open",
      score: 96,
      recommended_priority: "P1",
      reasons: [
        "Critical business impact",
        "Extreme urgency",
        "Affects core service",
      ],
    },
    {
      ticket_id: "INC-1019",
      title: "Payment workflow outage",
      category: "Application",
      service: "Customer Portal",
      status: "Open",
      score: 93,
      recommended_priority: "P1",
      reasons: [
        "Critical business impact",
        "Extreme urgency",
        "Affects core service",
        "Contains urgent keywords (outage, unavailable)",
      ],
    },
    {
      ticket_id: "INC-1028",
      title: "Users locked out after MFA reset",
      category: "Access",
      service: "Identity",
      status: "Open",
      score: 84,
      recommended_priority: "P1",
      reasons: [
        "Critical business impact",
        "High urgency",
        "Affects core service",
      ],
    },
    {
      ticket_id: "INC-1037",
      title: "Payment workflow outage",
      category: "Application",
      service: "Customer Portal",
      status: "Open",
      score: 83,
      recommended_priority: "P1",
      reasons: [
        "Critical business impact",
        "Extreme urgency",
        "Affects core service",
      ],
    },
    {
      ticket_id: "INC-1018",
      title: "VPN disconnects for remote staff",
      category: "Network",
      service: "Network Core",
      status: "Open",
      score: 73,
      recommended_priority: "P2",
      reasons: [
        "High business impact",
        "High urgency",
        "Affects core service",
      ],
    },
    {
      ticket_id: "INC-1004",
      title: "Portal timeout during checkout",
      category: "Application",
      service: "Customer Portal",
      status: "Open",
      score: 71,
      recommended_priority: "P2",
      reasons: [
        "Critical business impact",
        "High urgency",
        "Part of a recurring pattern",
      ],
    },
    {
      ticket_id: "INC-1007",
      title: "DNS resolution failure in branch office",
      category: "Network",
      service: "Network Core",
      status: "Open",
      score: 68,
      recommended_priority: "P2",
      reasons: [
        "High business impact",
        "High urgency",
        "Affects core service",
      ],
    },
    {
      ticket_id: "INC-1006",
      title: "Password reset emails not delivered",
      category: "Access",
      service: "Identity",
      status: "Open",
      score: 66,
      recommended_priority: "P2",
      reasons: [
        "High business impact",
        "High urgency",
        "Part of a recurring pattern",
      ],
    },
    {
      ticket_id: "INC-1011",
      title: "Checkout API returns 500 error",
      category: "Application",
      service: "Customer Portal",
      status: "Open",
      score: 59,
      recommended_priority: "P3",
      reasons: [
        "Critical business impact",
        "High urgency",
      ],
    },
    {
      ticket_id: "INC-1010",
      title: "SMTP relay failure for alerts",
      category: "Email",
      service: "Collaboration",
      status: "Open",
      score: 48,
      recommended_priority: "P3",
      reasons: [
        "Medium business impact",
        "High urgency",
        "Contains urgent keywords (failed)",
      ],
    },
    {
      ticket_id: "INC-1003",
      title: "Outlook mailbox sync delayed",
      category: "Email",
      service: "Collaboration",
      status: "Open",
      score: 30,
      recommended_priority: "P4",
      reasons: [
        "Medium business impact",
        "Medium urgency",
      ],
    },
    {
      ticket_id: "INC-1014",
      title: "Unattached disk still incurring cost",
      category: "Infrastructure",
      service: "Storage",
      status: "Open",
      score: 22,
      recommended_priority: "P4",
      reasons: [
        "Medium business impact",
        "Low urgency",
      ],
    },
  ],
  cloudCosts: {
    summary: {
      total_waste_estimated: 4250,
      idle_resources_count: 14,
      unattached_resources_count: 8,
      top_wasted_services: [
        { label: "EC2 / Virtual Machines", value: 1850, color: "var(--rose)" },
        { label: "EBS / Managed Disks", value: 1200, color: "var(--amber)" },
        { label: "RDS / SQL DBs", value: 850, color: "var(--violet)" },
        { label: "Elastic IPs", value: 350, color: "var(--sky)" },
      ],
    },
    resources: [
      { id: "i-0a1b2c3d4e5f6g7h8", provider: "AWS", service: "EC2", type: "t3.xlarge", status: "idle", cpu_usage_percent: 0, monthly_cost: 121.92, reason: "0% CPU for 14 days" },
      { id: "vm-reporting-prod-02", provider: "Azure", service: "Virtual Machines", type: "Standard_D4s_v3", status: "idle", cpu_usage_percent: 1, monthly_cost: 146.00, reason: "<2% CPU for 30 days" },
      { id: "vol-0z9y8x7w6v5u4t3s2", provider: "AWS", service: "EBS", type: "gp3 (500GB)", status: "unattached", cpu_usage_percent: null, monthly_cost: 40.00, reason: "Unattached for > 7 days" },
      { id: "disk-backup-old", provider: "Azure", service: "Managed Disks", type: "Premium SSD (1TB)", status: "unattached", cpu_usage_percent: null, monthly_cost: 135.17, reason: "Unattached snapshot accumulation" },
      { id: "eipalloc-0123456789", provider: "AWS", service: "Elastic IP", type: "IPv4", status: "unattached", cpu_usage_percent: null, monthly_cost: 3.60, reason: "Not attached to any running instance" },
      { id: "rds-dev-db-01", provider: "AWS", service: "RDS", type: "db.r5.large", status: "running", cpu_usage_percent: 0, monthly_cost: 420.00, reason: "Development DB with 0 connections for 7 days" },
      { id: "vm-test-env-01", provider: "Azure", service: "Virtual Machines", type: "Standard_B2s", status: "stopped", cpu_usage_percent: null, monthly_cost: 30.66, reason: "Stopped (Deallocated) but retaining OS disk cost" },
    ]
  }
};
